base = "https://phocks.eu.org"
client_id = "aIwvNY-qfcSTAJs3YYgNdQtJg7wpfDwrovOFWxAt1CA"
client_secret = "8A3LZXFmi0FJ7HeiEn_GIvSUdHXmTQ0Kljj0rw9EP78"
redirect = "urn:ietf:wg:oauth:2.0:oob"
token = "Hi9xskJy0UxjQ3cnRW8m9pCy9jVyNpDUP2iElelr_UE"
